# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'CourseWork' do

  # Pods for CourseWork
pod 'Alamofire'
pod 'IQKeyboardManagerSwift', '>= 6.0.4'
pod 'SDWebImage', '~> 4.0'
pod 'Fabric'
pod 'Crashlytics'

end
